Repository 2024-yju-capston-team3/project_fukuoka-album-backend-repo, pull requests merged in 2023-10, with the labels that each got.

#1 feat: Implement Auth endpoint with user signIn
  .gitignore
  app.ts
  controller/auth.ts
  module/jwt.ts
  package.json
  routes/auth.ts
  routes/index.ts
  tsconfig.json
Labels: ✨ Feature, 📬 API

#2 fix: fix signIn
  controller/auth.ts
Labels: 🐞 BugFix

#3 feat: Implement Express Auth Middleware
  controller/auth.ts
  middleware/authMiddleware.ts
  module/jwt.ts
  routes/auth.ts
  util/asyncWrapper.ts
  util/response.ts
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#4 fix(module/jwt): Fix token verification error
  .prettierignore
  .prettierrc
  app.ts
  controller/auth.ts
  middleware/authMiddleware.ts
  module/jwt.ts
  routes/auth.ts
  routes/index.ts
  src/app.ts
  src/controller/auth.ts
  src/middleware/authMiddleware.ts
  src/module/jwt.ts
  src/routes/auth.ts
  src/routes/index.ts
  src/util/asyncWrapper.ts
  src/util/response.ts
  tsconfig.json
Labels: 🐞 BugFix, 🔨 Refactor

#5 fix: Fix compiled js file's path
  package.json
  src/controller/authController.ts
  src/middleware/authMiddleware.ts
  src/routes/auth.ts
  tsconfig.json
Labels: 🐞 BugFix

#6 feat: Implement Upload feature
  .gitignore
  package.json
  src/controller/authController.ts
  src/controller/uploadController.ts
  src/middleware/authMiddleware.ts
  src/middleware/uploadMiddleware.ts
  src/module/jwt.ts
  src/routes/index.ts
  src/routes/upload.ts
  src/util/exception.ts
  src/util/jsonServerRequest.ts
  src/util/response.ts
Labels: ✨ Feature, 📬 API, ⚙ Setting

#7 feat: Implement userController
  package.json
  src/controller/uploadController.ts
  src/controller/userController.ts
  src/middleware/uploadMiddleware.ts
  src/routes/index.ts
  src/routes/upload.ts
  src/routes/user.ts
  src/util/exception.ts
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#8 refactor: Separate accessMiddleware and refreshMiddleware
  package.json
  src/app.ts
  src/controller/authController.ts
  src/controller/uploadController.ts
  src/controller/userController.ts
  src/middleware/authMiddleware.ts
  src/module/jwt.ts
  src/routes/auth.ts
  src/routes/user.ts
  src/util/jsonServerRequest.ts
  src/util/response.ts
  tsconfig.json
Labels: ✨ Feature, 🔨 Refactor, ⚙ Setting

#9 fix(controller): fix return value in storeTempImage function
  src/controller/uploadController.ts
  src/middleware/uploadMiddleware.ts
Labels: 🐞 BugFix, ✨ Feature

#10 feat(upload): add delete endpoint
  src/controller/uploadController.ts
  src/routes/upload.ts
  src/util/response.ts
Labels: ✨ Feature, 📬 API
